### ISSUE TITLE
All devices are removed, not only device older than 20 days

### ISSUE THREAD

**Issue by Nickbert7** [crobibero/jellyfin-plugin-sessioncleaner#1]
Thank you for the plugin.
Unfortunately currently all devices are getting removed with the task, not only devices older than 20 days. (If I'm correct this should be the current hardcoded value, right?)
I tested it on the latest Unsable server as I don't wanted to test is in my prduction eviroment.

**Comment by crobibero** [comment]
I pushed a new plugin update that should fix this

**Comment by Nickbert7** [comment]
Yes, it it fixed now.
I created a few new sessions and modified last activity date for them in the db.
Old devices now get removed fine and currend devices are still there.
